language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-7.0
  - Pharo-6.0
  - Pharo-5.0
  - Pharo64-7.0
  - Pharo64-6.0

allow_failures:
  - smalltalk: Pharo-7.0
  - smalltalk: Pharo64-7.0
  
